### PR TITLE
feat: support rock-4se

### PR DESCRIPTION
**Pull request by borancar**
Add support for Rock 4 SE using Rockchip TPL for DRAM initialization. U-boot mainline is unable to configure DRAM at this moment.

### CODE REVIEW

**Comment by borancar** [comment]
I have tested this on multiple Rock 4 SE V1.53 boards.

**Comment by frezbo** [comment]
Is this good to review?

**Comment by borancar** [comment]
> Is this good to review?

Yes

**Review by frezbo — APPROVED** [review]

**Pull request merged**
